services:
  sellsy:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules # mirror node_module on host machine
    stdin_open: true
    tty: true